### ISSUE TITLE
Login Behavior

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-express-react-example#15]
If I'm logged in, and go to the home page of this app, then click 'login', I'm taken back to the profile page. This is odd behavior. Why can't I go to the login form and try to login?

**Comment by rorheden** [comment]
I don't feel that it's a common pattern for someone to be able to access the login page after one is logged in? If you are logged in and want to log in with another user, the pattern is usually to logout then login again? Let me know if I'm misunderstanding something or if there's a scenario for this that I have missed:)

**Comment by robertjd** [comment]
This behavior is intentional and is codified in our framework spec: you have to logout before you can log in as another user.

**Comment by rdegges** [comment]
I think the issue is that we don't use template masking to hide the login button once you're logged in. We should do this so you can't see that login option and click it.

**Comment by robertjd** [comment]
Yes, that's something we should fix in this example.
