### ISSUE TITLE
Login Page Asks for Username or Email

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-express-react-example#16]
It should only ask for email, since there's no way to specify a username anywhere in this application. This is confusing.

**Comment by rorheden** [comment]
This actually originates from the view model.

See: https://github.com/stormpath/express-stormpath/blob/master/lib/config.yml#L137

@robertjd Do you have any input here?

**Comment by robertjd** [comment]
The default makes sense to me, as we don't know which way the developer will go with their application (do they want to support username+email, or just one or the other?).  As such I don't see a need to change anything here, it's just a sample app for getting started and seeing what's possible.
