### ISSUE TITLE
Error: API key ID and secret is required.

### ISSUE THREAD

**Issue by scheung38** [stormpath/stormpath-express-react-example#21]
Git cloned this project but I supposed you need the stormpath.yml to provide API key ID and secret? Where to place this place and what should be the content?

✖ Initializing Stormpath
Error: API key ID and secret is required.

Is this correct syntax?

client:
  apiKey:
    id: '**redacted**'
    secret: '**redacted**'
application:
  href: 'https://api.stormpath.com/v1/applications/**redacted**'

**Comment by rorheden** [comment]
Hi Sebastian,

The formatting of you YAML-file looks correct. The `stormpath.yml` file should be placed in the root of your application directory.

Did you place it there?

Also, I removed your API key id and secret from your comment. Remember that these values are sensitive and should never be shared in public. I recommend that you remove your API key and create a new one.

**Comment by scheung38** [comment]
It is still complaining cannot find API id and secret? No repo?

This is confusing, do I also need to create a Directory for the Application as well?

**Comment by scheung38** [comment]
I just created and downloaded 

apiKey-5OOG7O2JQCLJF00ZKNM0PC9X8.properties

and there is the api id and secret as well as HREF from the website

and copied, pasted into the 

stormpath.yaml file

client:
  apiKey:
    id: '<my id>'
    secret: '<my secret> '
application:
  href: 'https://api.stormpath.com/v1/accounts/<my href>'

But npm install

 No repository field.

**Comment by mdeggies** [comment]
Hey @scheung38, the indentation matters for yml files. It should look exactly like this:

```
client:
  apiKey:
    id: $ID
    secret: $SECRET
application:
  href: https://api.stormpath.com/v1/applications/$APP_HREF
```
