### ISSUE TITLE
Add custom data update to example project

### ISSUE THREAD

**Issue by mdeggies** [stormpath/stormpath-express-react-example#8]
In the [express-stormpath sample project](https://github.com/stormpath/express-stormpath-sample-project), it shows how to easily update a custom data field (favorite-color). Can you add something like this to the react example project?

**Comment by rorheden** [comment]
This is in progress. See: https://github.com/stormpath/stormpath-sdk-react/pull/111

**Comment by rorheden** [comment]
This has been fixed. So closing issue.
